input {
  tcp {
    port => 5000
    codec => json_lines
  }
  udp {
    port => 5000
    codec => json_lines
  }
}

filter {
  if [message] =~ /^\{.*\}$/ {
    json {
      source => "message"
    }
  }

  if [application_name] == "gateway-server"{
      mutate {
        add_field => { "service_type" => "gateway" }
        add_field => { "service_tier" => "infrastructure" }
        add_tag => ["api-gateway"]
      }
  }

  if [application_name] == "recipe-service"{
      mutate {
        add_field => { "service_type" => "business" }
        add_field => { "service_tier" => "application" }
        add_tag => ["recipe-service"]
      }
  }

  if [application_name] == "social-service"{
      mutate {
        add_field => { "service_type" => "business" }
        add_field => { "service_tier" => "application" }
        add_tag => ["social-service"]
      }
  }

    if [application_name] == "user-service"{
        mutate {
          add_field => { "service_type" => "business" }
          add_field => { "service_tier" => "application" }
          add_tag => ["user-service"]
        }
    }

  mutate {
    add_field => { "[@metadata][index_prefix]" => "spring-logs" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "%{[@metadata][index_prefix]}-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}